# Generated by Django 2.1.5 on 2019-01-05 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='название')),
                ('description', models.TextField(blank=True, default='', verbose_name='описание')),
                ('bump_limit', models.PositiveSmallIntegerField(default=500, verbose_name='бамп лимит')),
                ('thread_limit', models.PositiveSmallIntegerField(default=200, verbose_name='максимум тредов')),
                ('filesize_limit', models.PositiveIntegerField(default=5242880, verbose_name='лимит на размер файла')),
            ],
            options={
                'verbose_name': 'доска',
                'verbose_name_plural': 'доски',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='категория')),
                ('order', models.SmallIntegerField(verbose_name='порядок')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='доска скрыта')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.PositiveIntegerField(blank=True, db_index=True, verbose_name='id поста')),
                ('is_op_post', models.BooleanField(default=False, verbose_name='первый пост в треде')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='время')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='удален')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('poster', models.CharField(blank=True, max_length=32, null=True, verbose_name='постер')),
                ('tripcode', models.CharField(blank=True, max_length=32, verbose_name='трипкод')),
                ('email', models.CharField(blank=True, max_length=32, verbose_name='email')),
                ('topic', models.CharField(blank=True, max_length=48, verbose_name='тема')),
                ('password', models.CharField(blank=True, max_length=64, verbose_name='пароль')),
                ('message', models.TextField(blank=True, verbose_name='сообщение')),
            ],
            options={
                'verbose_name': 'пост',
                'verbose_name_plural': 'посты',
                'ordering': ['id'],
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='закреплен')),
                ('is_closed', models.BooleanField(default=False, verbose_name='закрыт')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='удален')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread', to='board.Board', verbose_name='доска')),
            ],
            options={
                'verbose_name': 'тред',
                'verbose_name_plural': 'треды',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='board.Thread', verbose_name='тред'),
        ),
        migrations.AddField(
            model_name='board',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board', to='board.Category', verbose_name='категория'),
        ),
    ]
