# Generated by Django 2.1.5 on 2019-01-06 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_squashed_0005_auto_20190106_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='lasthit',
            field=models.DateTimeField(auto_now=True, verbose_name='последний пост'),
        ),
    ]
