# Generated by Django 2.1.5 on 2019-01-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('board', '0001_squashed_0007_auto_20190112_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='fullname',
            field=models.CharField(db_index=True, max_length=255,
                                   verbose_name='оригинальное название'),
        ),
    ]
