# Generated by Django 2.1.5 on 2019-01-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='board_name',
            field=models.CharField(max_length=48,
                                   verbose_name='название доски'),
        ),
    ]
