# Generated by Django 2.1.5 on 2019-01-06 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_thread_lasthit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_id',
            new_name='num',
        ),
    ]
