# Generated by Django 2.1.5 on 2019-01-07 03:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('board', '0002_spamword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spamword',
            name='created',
            field=models.DateTimeField(auto_now_add=True,
                                       verbose_name='создано'),
        ),
    ]
