# Generated by Django 2.1.5 on 2019-01-06 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20190105_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='poster',
        ),
        migrations.AddField(
            model_name='board',
            name='trip_permit',
            field=models.BooleanField(default=False, verbose_name='разрешены трип коды'),
        ),
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(blank=True, max_length=48, null=True, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='post',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.CharField(blank=True, max_length=128, verbose_name='тема'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tripcode',
            field=models.CharField(blank=True, max_length=48, verbose_name='трипкод'),
        ),
    ]
