# Generated by Django 2.1.5 on 2019-01-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('board', '0003_board_enable_roulette'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='image_required',
            field=models.BooleanField(default=False,
                                      verbose_name='требовать изображение'),
        ),
    ]
