# Generated by Django 2.1.5 on 2019-01-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20190106_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='parent',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=0, verbose_name='родитель'),
            preserve_default=False,
        ),
    ]
