# Generated by Django 2.1.5 on 2019-01-11 01:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('board', '0003_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='fullname',
            field=models.CharField(db_index=True, default='test',
                                   max_length=255,
                                   verbose_name='оригинальное название'),
            preserve_default=False,
        ),
    ]
