# Generated by Django 2.1.5 on 2019-01-12 05:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('board', '0004_file_fullname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ban',
            name='created',
        ),
        migrations.AddField(
            model_name='ban',
            name='banned_at',
            field=models.DateTimeField(auto_now_add=True,
                                       default=django.utils.timezone.now,
                                       verbose_name='забанен'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ban',
            name='until',
            field=models.DateTimeField(blank=True,
                                       default=django.utils.timezone.now,
                                       verbose_name='бан до'),
            preserve_default=False,
        ),
    ]
