# Generated by Django 2.1.5 on 2019-01-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('board', '0004_auto_20190107_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sage',
            field=models.BooleanField(blank=True, default=False,
                                      verbose_name='sage'),
        ),
    ]
