# Generated by Django 2.1.5 on 2019-01-06 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20190106_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='message',
        ),
        migrations.RemoveField(
            model_name='post',
            name='topic',
        ),
        migrations.AddField(
            model_name='post',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='сообщение'),
        ),
        migrations.AddField(
            model_name='post',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='тема'),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(blank=True, default='Аноним', max_length=48, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='post',
            name='password',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='пароль'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='board.Thread', verbose_name='тред'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tripcode',
            field=models.CharField(blank=True, default='', max_length=48, verbose_name='трипкод'),
        ),
    ]
