# Generated by Django 2.1.5 on 2019-01-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_post_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='default_name',
            field=models.CharField(default='Аноним', max_length=48, verbose_name='имя в постах'),
        ),
    ]
