# Generated by Django 2.1.5 on 2019-01-07 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('board', '0005_post_sage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='IP')),
                ('reason', models.TextField(blank=True, default='',
                                            verbose_name='причина')),
                ('duration', models.DurationField(verbose_name='длительность')),
                ('created', models.DateTimeField(auto_now_add=True,
                                                 verbose_name='создан')),
                ('board',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='bans', to='board.Board',
                                   verbose_name='доска')),
            ],
            options={
                'verbose_name': 'бан',
                'verbose_name_plural': 'баны',
            },
        ),
    ]
