# Generated by Django 2.1.5 on 2019-01-06 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_board_default_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='name',
            new_name='board',
        ),
        migrations.AddField(
            model_name='board',
            name='board_name',
            field=models.CharField(blank=True, max_length=48, verbose_name='название доски'),
        ),
    ]
