# Generated by Django 2.1.5 on 2019-01-12 05:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('board', '0005_auto_20190112_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ban',
            name='banned_at',
            field=models.DateTimeField(default=django.utils.timezone.now,
                                       verbose_name='забанен'),
        ),
    ]
