# Generated by Django 2.1.5 on 2019-01-15 08:46

from django.db import migrations, models

import apps.board.helpers


class Migration(migrations.Migration):
    dependencies = [
        ('board', '0005_auto_20190113_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='op',
            field=models.BooleanField(blank=True, default=False,
                                      verbose_name='OP'),
        ),
        migrations.AlterField(
            model_name='file',
            name='thumbnail',
            field=models.ImageField(blank=True, height_field='tn_height',
                                    upload_to=apps.board.helpers.resolve_thumb_path,
                                    verbose_name='thumbnail',
                                    width_field='tn_width'),
        ),
    ]
