# Generated by Django 2.1.5 on 2019-01-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('board', '0006_ban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ban',
            name='ip',
            field=models.GenericIPAddressField(db_index=True,
                                               verbose_name='IP'),
        ),
    ]
