# Generated by Django 2.1.5 on 2019-01-16 05:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('board', '0006_auto_20190115_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='image_required',
        ),
        migrations.AddField(
            model_name='board',
            name='file_required',
            field=models.BooleanField(default=True,
                                      verbose_name='требовать файл в оп посте'),
        ),
        migrations.AddField(
            model_name='board',
            name='max_files',
            field=models.PositiveSmallIntegerField(default=4,
                                                   verbose_name='максимум файлов в посте'),
        ),
    ]
