# Generated by Django 2.1.5 on 2019-01-08 01:30

import netfields.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('board', '0007_auto_20190107_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ban',
            name='ip',
        ),
        migrations.AddField(
            model_name='ban',
            name='inet',
            field=netfields.fields.CidrAddressField(db_index=True,
                                                    default='127.0.0.1',
                                                    max_length=43,
                                                    verbose_name='CIDR'),
            preserve_default=False,
        ),
    ]
