# Generated by Django 2.1.5 on 2019-01-08 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('board', '0008_auto_20190108_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='ban',
            name='for_all_boards',
            field=models.BooleanField(default=False,
                                      verbose_name='для всех досок'),
        ),
        migrations.AlterField(
            model_name='ban',
            name='board',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    related_name='bans', to='board.Board',
                                    verbose_name='доска'),
        ),
    ]
