# Generated by Django 2.1.5 on 2019-01-08 05:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('board', '0009_auto_20190108_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='trip_required',
            field=models.BooleanField(default=False,
                                      verbose_name='генерировать трип код'),
        ),
    ]
