# Generated by Django 2.1.5 on 2019-01-08 06:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('board', '0012_auto_20190108_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='timestamp',
        ),
    ]
