# Generated by Django 2.1.5 on 2019-01-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('board', '0013_auto_20190108_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='trip_permit',
            new_name='enable_trips',
        ),
        migrations.AddField(
            model_name='board',
            name='enable_sage',
            field=models.BooleanField(default=True,
                                      verbose_name='sage включена'),
        ),
        migrations.AddField(
            model_name='board',
            name='enable_subject',
            field=models.BooleanField(default=True,
                                      verbose_name='разрешены темы постов'),
        ),
    ]
