# Generated by Django 2.1.5 on 2019-01-09 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('board', '0015_auto_20190109_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thread',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='posts', to='board.Thread', verbose_name='тред'),
        ),
    ]
